In [1]:
import numpy as np
import torch
import time

# Numpy linalgebra basic functions

아래와 같은 기본적인 linear algebra 함수들의 사용법을 알아보겠습니다.

### Matrix and vector products
*   Rank
*   Trace
*   Determinant
*   Inverse
*   Power
*   Eigenvalue
*   Norm
*   Singular Value Decomposition  


예제에 사용할 random array를 만듭니다.

In [2]:
X = np.random.rand(3, 3)
X2 = np.random.rand(3, 3)

print(f"X: \n{X} \n X2: \n{X2}")

X: 
[[0.3787661  0.32064462 0.10324807]
 [0.12700387 0.98621645 0.68072946]
 [0.51770779 0.69754444 0.06783047]] 
 X2: 
[[0.5336999  0.3653256  0.28804943]
 [0.29091874 0.74885801 0.93731009]
 [0.60591132 0.76748547 0.31153618]]


In [3]:
# Rank of a matrix
print("Rank of X:", np.linalg.matrix_rank(X))

Rank of X: 3


In [4]:
# Trace of matrix
print("\nTrace of X:", np.trace(X))


Trace of X: 1.4328130292241563


In [5]:
# Dot product of matrice
print("\nDot product of X, X2:", np.dot(X, X2))


Dot product of X, X2: [[0.35798813 0.45773163 0.4418123 ]
 [0.76715249 1.30738382 1.17304588]
 [0.5203286  0.76355255 0.82407252]]


In [6]:
# Matmul of matrice
print("\nMatmul of X, X2:", np.matmul(X, X2))


Matmul of X, X2: [[0.35798813 0.45773163 0.4418123 ]
 [0.76715249 1.30738382 1.17304588]
 [0.5203286  0.76355255 0.82407252]]


In [7]:
# Determinant of a matrix
print("\nDeterminant of X:", np.linalg.det(X))


Determinant of X: -0.08784493956970786


In [8]:
# Inverse of matrix X
print("\nInverse of X:\n", np.linalg.inv(X))

identity = np.matmul(X, np.linalg.inv(X))
print(f"X @ X^-1 :\n", identity)


Inverse of X:
 [[ 4.64390456 -0.57226562 -1.32560046]
 [-3.91376224  0.31601643  2.78586723]
 [ 4.80370411  1.11794683 -3.78874705]]
X @ X^-1 :
 [[ 1.00000000e+00  1.70172188e-17  2.42208124e-16]
 [ 1.83371008e-16  1.00000000e+00  4.58467429e-17]
 [-1.50625137e-16 -4.40241099e-18  1.00000000e+00]]


In [9]:

# Power of matrix X
print("\nMatrix X raised to power 3:\n",
           np.linalg.matrix_power(X, 3))


Matrix X raised to power 3:
 [[0.2916157  0.76328527 0.38943298]
 [0.76640651 2.14590961 1.11689609]
 [0.51147249 1.36307983 0.68266867]]


In [10]:
# Eigenvalue of matrix X
print("\nEigenvalue of X are:\n",
      np.linalg.eig(X))


Eigenvalue of X are:
 (array([-0.26018929,  0.23091619,  1.46208612]), array([[-0.10296105, -0.77966451, -0.28830347],
       [ 0.48483822,  0.48646945, -0.80921966],
       [-0.86852226, -0.39429775, -0.51190298]]))


In [11]:
# Norm of matrix X
print("\Norm of X are:\n",
      np.linalg.norm(X, axis=-1))


Eigenvalue of X are:
 [0.50688943 1.20504999 0.87131542]


In [12]:
# Singular Value Decomposition of matrix X
u, k, v = np.linalg.svd(X)
print("\nSingular Value Decomposition of X are:\n",
      np.linalg.svd(X))


Singular Value Decomposition of X are:
 (array([[-0.29981116,  0.42854301, -0.85232867],
       [-0.78723723, -0.6157829 , -0.03269507],
       [-0.53886066,  0.66118251,  0.5219836 ]]), array([1.47144862, 0.53931285, 0.11069573]), array([[-0.3347129 , -0.84841454, -0.41007322],
       [ 0.79065442, -0.01609648, -0.61205106],
       [-0.51267228,  0.52908759, -0.6761904 ]]))


In [13]:
print("u @ u^T:\n", np.matmul(u, u.T))
print("v @ v^T:\n", np.matmul(v, v.T))
check = u@np.diag(k)@v - X
print("check whether svd is correct or not: \n", np.where(check < pow(1, -10), True, False))

u @ u^T:
 [[ 1.00000000e+00 -2.70162777e-16 -9.66423797e-17]
 [-2.70162777e-16  1.00000000e+00 -1.88225868e-16]
 [-9.66423797e-17 -1.88225868e-16  1.00000000e+00]]
v @ v^T:
 [[ 1.00000000e+00  1.35699650e-17 -1.54947844e-16]
 [ 1.35699650e-17  1.00000000e+00  9.47348854e-17]
 [-1.54947844e-16  9.47348854e-17  1.00000000e+00]]
check whether svd is correct or not: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


위 내용들을 torch library를 사용해서 수행해보겠습니다.

In [26]:
X = torch.rand(3, 3)
X2 = torch.rand(3, 3)

In [27]:
# Rank of a matrix
print("Rank of X:", torch.linalg.matrix_rank(X))

Rank of X: tensor(3)


In [28]:
# Trace of matrix
print("\nTrace of X:", torch.trace(X))


Trace of X: tensor(0.8201)


In [31]:
# Dot product of matrice
print("\nDot product of X, X2:", torch.dot(X[0], X2[0]))


Dot product of X, X2: tensor(0.0901)


In [32]:
# Matmul of matrice
print("\nMatmul of X, X2:", torch.matmul(X, X2))


Matmul of X, X2: tensor([[0.0972, 0.6361, 0.3070],
        [0.1450, 1.0986, 0.3721],
        [0.1250, 0.8109, 0.2408]])


In [33]:
# Determinant of a matrix
print("\nDeterminant of X:", torch.linalg.det(X))


Determinant of X: tensor(-0.1084)


In [34]:
# Inverse of matrix X
print("\nInverse of X:\n", torch.linalg.inv(X))

identity = torch.matmul(X, torch.linalg.inv(X))
print(f"X @ X^-1 :\n", identity)


Inverse of X:
 tensor([[-0.5753, -0.6317,  1.8640],
        [ 0.0906,  3.8057, -4.2118],
        [ 2.1698, -0.9948,  0.8669]])
X @ X^-1 :
 tensor([[ 1.0000e+00, -5.9605e-08,  8.9407e-08],
        [ 0.0000e+00,  1.0000e+00,  1.0431e-07],
        [ 5.9605e-08,  5.9605e-08,  1.0000e+00]])


In [35]:
# Power of matrix X
print("\nMatrix X raised to power 3:\n",
           torch.linalg.matrix_power(X, 3))


Matrix X raised to power 3:
 tensor([[0.4148, 0.2143, 0.3710],
        [1.1078, 0.4675, 0.6473],
        [0.8177, 0.3236, 0.4369]])


In [36]:
# Singular Value Decomposition of matrix X
u, k, v = torch.linalg.svd(X)
print("\nSingular Value Decomposition of X are:\n",
      torch.linalg.svd(X))


Singular Value Decomposition of X are:
 torch.return_types.linalg_svd(
U=tensor([[-0.1794,  0.9830,  0.0391],
        [-0.7552, -0.1121, -0.6458],
        [-0.6305, -0.1454,  0.7625]]),
S=tensor([1.5021, 0.4407, 0.1638]),
Vh=tensor([[-0.8936, -0.3529, -0.2772],
        [-0.3375,  0.1211,  0.9335],
        [ 0.2958, -0.9278,  0.2273]]))


# Parallel computation using numpy - How to substitute for loop

multi dimensional array 계산을 할 때, 단순히 `for loop`를 사용할 경우 for loop의 길이만큼 computational cost가 증가합니다.

하지만 `numpy`는 `C`로 작성된 함수를 사용해 multi dimensional array를 계산하기 때문에, for loop에 비해 훨씬 좋은 계산 효율을 보여줍니다.

예제를 통해 알아보겠습니다.

In [14]:
array1 = np.random.rand(100)


주어진 array의 원소들을 절댓값으로 수정하여 반환하는 함수를 사용하여,

`numpy`와 `for loop` 사용 시의 computational time을 비교하겠습니다.

In [15]:
# python decorator to record function execution time
def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        computation_time = end_time - start_time
        print(f"Execution time of {func.__name__}: {computation_time} seconds")
        return computation_time
    return wrapper

@timer
def take_abs_using_for_loop(array):
  for i in range(len(array)):
    array[i] = np.abs(array[i])
  return array

@timer
def take_abs_using_parallelism(array):
  return np.abs(array)

`timer` 는 함수의 실행시간을 측정하기 위해 작성된 `decorator`입니다.

In [16]:
time1 = take_abs_using_for_loop(array1)
time2 = take_abs_using_parallelism(array1)

Execution time of take_abs_using_for_loop: 0.00022935867309570312 seconds
Execution time of take_abs_using_parallelism: 5.4836273193359375e-06 seconds


In [17]:
print(f"computation using parallelism is {time1 / time2} times faster than for loop.")

computation using parallelism is 41.82608695652174 times faster than for loop.


위의 multi dimensional array 예제에서, for loop를 사용한 경우보다 numpy를 사용한 경우가 26.75배 빠른 것을 알 수 있습니다.

# torch tensor 소개

torch tensor는 numpy와 비슷하게, C로 작성된 효율 좋은 multi dimensional array 계산 기능이 있습니다.

거기에 더해, `require_grad=True`로 설정되어 있는 tensor들에 대해서, cumulative automatic differentiation을 통한 gradient 추적 기능을 제공합니다.

이 기능은 추후 neural network를 학습시키는 코드를 짤 때 핵심적인 기능이 됩니다.

![image](https://drive.google.com/uc?export=download&id=1KY7DXZDwKj65vc5fm2bX_s4NACFoyH6K)

지금은 

- automatic differentation을 통한 gradient 추적이 어떻게 이뤄지는지 
- 추적이 필요하지 않을 때는 어떻게 멈출 수 있는지

를 알아보겠습니다.

In [18]:
import torch

one linear network를 정의합니다.

In [19]:
import torch

# Let's define a simple one layer network: f(x) = wx + b.
x = torch.rand(4, requires_grad=True)
w = torch.rand(4, requires_grad=True)
b = torch.rand(4, requires_grad=True)

# Forward pass
z = w * x 
z = z + b 
z = z.mean()

gradient 추적을 위해, z를 scalar로 만들어 줍니다.

In [20]:
# New computation using z
q = z.detach()

비교를 위해, tensor value 자체는 z와 같지만, gradient 추적 정보는 `.detach()` 를 사용해서 없애버린 tensor q를 선언합니다.

z, q의 computational graph가 생각대로 처리되었는지 확인합니다.

In [21]:
print("Dose z requires gradient information? :", z.requires_grad)
print("Dose q requires gradient information? :", q.requires_grad)

Dose z requires gradient information? : True
Dose q requires gradient information? : False


q 는 gradient 추적을 위한 computational graph가 없기 때문에, `.backward()` 호출을 통한 gradient backpropagation이 불가능합니다.

`.backward()`를 하기 전에 linear network의 parameter가 gradient를 가지고 있는지 확인해보겠습니다.

In [22]:
print(w.grad)  
print(b.grad) 

None
None


아직 z에서 시작되는 gradient backpropagation을 수행하지 않아서, gradient 정보가 없는 모습입니다.

In [23]:
z.backward()

In [24]:
print(w.grad)
print(x / 4)  
print(b.grad) 

tensor([0.1176, 0.1427, 0.0594, 0.1226])
tensor([0.1176, 0.1427, 0.0594, 0.1226], grad_fn=<DivBackward0>)
tensor([0.2500, 0.2500, 0.2500, 0.2500])
